### ISSUE TITLE
Rewriter choke on a relative URL inside a querystring

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-scraperlib#321]
From https://farm.zimit.kiwix.org/pipeline/899453d8-6002-46a5-8c36-cc2f1c4783ef/debug

```
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 695, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 616, in run
    return warc2zim(warc2zim_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/main.py", line 168, in main
    return converter.run()
           ^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 384, in run
    self.add_items_for_warc_record(record)
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 946, in add_items_for_warc_record
    payload_item = WARCPayloadItem(
                   ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/items.py", line 56, in __init__
    ).rewrite(pre_head_template, post_head_template)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 108, in rewrite
    return self.rewrite_html(pre_head_template, post_head_template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 225, in rewrite_html
    rel_static_prefix = self.url_rewriter.get_document_uri(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/url_rewriting.py", line 354, in get_document_uri
    PurePosixPath(item_url).relative_to(
  File "/usr/lib/python3.12/pathlib.py", line 684, in relative_to
    raise ValueError(f"'..' segment in {str(other)!r} cannot be walked")
ValueError: '..' segment in 'portalvwco.catalog.srv.br/common/nessComponents/xtree.html?css=../../prg' cannot be walked

```

Not sure if that's something we just cant support (if so, why are we crashing?) or a legitimate bug

**Comment by benoit74** [comment]
Problem is in fact a bit wider. See https://github.com/openzim/overview/issues/90 which needs to be solved before we can make any progress on this issue.

**Comment by benoit74** [comment]
Things have settled in the parent: ZIM path with "dot segments" are forbidden.

Question is now how do we replace these ZIM path.

For now, we have following behavior: `https://example.com/abc/de?f=12/../34` URL is assigned ZIM path `example.com/abc/de?f=12/../34` which is incorrect

I see following alternatives:
- encode the dots in dot-segments (any only in these): ZIM path would become `example.com/abc/de?f=12/%2E%2E/34` ; I feel like this is pretty ugly especially because it means the relative URL to access this from `example.com/abc/` HTML page would become `de%3Ff=12/%252E%252E/34` (we need to double encode the percent sign ... pretty ugly)
- add any character to transform the dot-segment in something else: for instance ZIM path could become `example.com/abc/de?f=12/_../34` (URL to access `abc/de%3Ff=12/_../34`)
- completely remove the dot-segment: ZIM path could become `example.com/abc/de?f=12//34` (URL to access `abc/de%3Ff=12//34`)

It is important to note that:
- all these transformations put us a risk of a collision, but since we have less flexibility in ZIM path than in URLs, there is de-facto a risk of conflict. The question is more what is less likely to occur and what is less ugly to read
- all these transformations will likely cause some things in the ZIM to be broken if the dot-segment was in the query parameter because this is very likely used by JS code to infer some logic

Both are intrinsic limitations of current "zimit" approach and ZIM path requirements (no query-string, only a path ; no dot-segments now)

**Comment by benoit74** [comment]
Miss-click, and my comment was incomplete, it is now.
